# Joining of groups in single csv file

In [7]:
import numpy as np
import pandas as pd
import numpy as np

In [3]:
user_features = pd.read_csv('../data/processed/user_features.csv')

In [4]:
user_features

,user_id,gender,married,has_children,home_country,tenure,age,seats_avg,checked_bags_avg,overcarrier,total_trips,cancellation_rate,unique_flight_destination,taken_flights,frequent_destinations,sessions_booking_rate,discount_booking_rate,booked_flight,booked_hotel
0,94883,F,True,False,usa,1509,54,1.5,0.5,False,2,0.0,2.0,2,1.0,0.250,0.0,True,True
1,101486,F,True,True,usa,1499,53,1.0,0.0,False,2,0.0,1.0,2,0.5,0.250,0.0,True,True
2,101961,F,True,False,usa,1499,45,1.0,0.4,False,5,0.0,5.0,5,1.0,0.625,0.2,True,True
3,106907,F,True,True,usa,1492,47,NaN,NaN,NaN,1,1.0,1.0,0,inf,0.000,NaN,False,False
4,118043,F,False,True,usa,1478,53,2.0,1.0,False,5,0.0,3.0,5,0.6,0.625,0.6,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5777,780167,F,True,True,usa,1067,51,1.5,0.0,False,2,0.0,2.0,2,1.0,0.250,0.5,True,True
5778,785186,F,True,True,usa,1065,46,1.0,0.0,False,2,0.0,2.0,2,1.0,0.250,0.0,True,True
5779,792549,F,False,False,usa,1062,48,1.0,0.5,False,4,0.0,4.0,4,1.0,0.500,0.0,True,True
5780,811077,F,True,True,usa,1056,47,1.0,0.0,False,1,0.0,1.0,1,1.0,0.125,0.0,True,True
5781,844489,M,False,True,usa,1044,25,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0.000,NaN,False,False

In [8]:
user_features['group'] = None

In [9]:
user_features

,user_id,gender,married,has_children,home_country,tenure,age,seats_avg,checked_bags_avg,overcarrier,total_trips,cancellation_rate,unique_flight_destination,taken_flights,frequent_destinations,sessions_booking_rate,discount_booking_rate,booked_flight,booked_hotel,group
0,94883,F,True,False,usa,1509,54,1.5,0.5,False,2,0.0,2.0,2,1.0,0.250,0.0,True,True,None
1,101486,F,True,True,usa,1499,53,1.0,0.0,False,2,0.0,1.0,2,0.5,0.250,0.0,True,True,None
2,101961,F,True,False,usa,1499,45,1.0,0.4,False,5,0.0,5.0,5,1.0,0.625,0.2,True,True,None
3,106907,F,True,True,usa,1492,47,NaN,NaN,NaN,1,1.0,1.0,0,inf,0.000,NaN,False,False,None
4,118043,F,False,True,usa,1478,53,2.0,1.0,False,5,0.0,3.0,5,0.6,0.625,0.6,True,True,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5777,780167,F,True,True,usa,1067,51,1.5,0.0,False,2,0.0,2.0,2,1.0,0.250,0.5,True,True,None
5778,785186,F,True,True,usa,1065,46,1.0,0.0,False,2,0.0,2.0,2,1.0,0.250,0.0,True,True,None
5779,792549,F,False,False,usa,1062,48,1.0,0.5,False,4,0.0,4.0,4,1.0,0.500,0.0,True,True,None
5780,811077,F,True,True,usa,1056,47,1.0,0.0,False,1,0.0,1.0,1,1.0,0.125,0.0,True,True,None
5781,844489,M,False,True,usa,1044,25,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0.000,NaN,False,False,None

In [5]:
family_travelers = pd.read_csv('../data/groups/family_traveler.csv')
user_features.loc[user_features["user_id"].isin(family_travelers['user_id']), 'group'] = 'family_travelers'

In [24]:
low_income = pd.read_csv('../data/groups/low_income.csv')
user_features.loc[user_features["user_id"].isin(low_income['user_id']), 'group'] = 'low_income'

In [25]:
luxus = pd.read_csv('../data/groups/luxus.csv')
user_features.loc[user_features["user_id"].isin(luxus['user_id']), 'group'] = 'luxus'

In [27]:
no_booker = pd.read_csv('../data/groups/no_bookers_group.csv')
user_features.loc[user_features["user_id"].isin(no_booker['user_id']), 'group'] = 'no_booker'

In [28]:
overcarriers = pd.read_csv('../data/groups/overcarriers.csv')
user_features.loc[user_features["user_id"].isin(overcarriers['user_id']), 'group'] = 'overcarriers'

In [29]:
seniors = pd.read_csv('../data/groups/seniors.csv')
user_features.loc[user_features["user_id"].isin(seniors['user_id']), 'group'] = 'seniors'

In [30]:
singles = pd.read_csv('../data/groups/singles.csv')
user_features.loc[user_features["user_id"].isin(singles['user_id']), 'group'] = 'singles'

In [31]:
young = pd.read_csv('../data/groups/young.csv')
user_features.loc[user_features["user_id"].isin(young['user_id']), 'group'] = 'young'

In [1]:
user_features.to_csv("results/users_with_groups.csv", index=False)

KeyboardInterrupt

## Perks analysis
Could be done for groups without a clear perk (obtained form domain knowledge)